### ISSUE TITLE
Misplaced files after running synx

### ISSUE THREAD

**Issue by mathonsunday** [venmo/synx#101]
After running synx on our project my file system had a new Testing folder within our project folder that included some tests that should have been with the other tests in the separate Testing folder we have. The organization of the files in the Xcode project looked correct. When I pushed the app to our remote repo, the Testing folder within our main project folder didn't exist. As a result the files that had been put in that folder were no longer accessible to anyone pulling from the remote repo. 

I have the output from running synx but it contains sensitive information related to the purpose of the app  we are developing at LinkedIn so won't share it publicly. I will share the relevant parts with names changed to protect sensitive information.

From looking at the output I have an idea of what went wrong. In the "Syncing files that are included in Xcode project..." step the file structure for the Testing folder included all the files in their right place except for one missing one that ended up in the new Testing folder subfolder of our main project folder.

[Link to what the output looks like](http://imgur.com/rqRBdHE)

 In  "Syncing files that are not included in Xcode project.." step the structure of the Testing folder 
includes that exact missing file in the right place but doesn't include the other test that ended up in the Testing subfolder of our main project folder. 

[Link to what the output looks like](http://imgur.com/BSIkxnT)

Even after fixing this issue locally and pushing it, the file structure in our remote repo is still wrong. 

I appreciate help understanding this issue and avoiding it in the future.

**Comment by ayanonagon** [comment]
> The organization of the files in the Xcode project looked correct. When I pushed the app to our remote repo, the Testing folder within our main project folder didn't exist.

That makes me think that your issue might be related to https://github.com/venmo/synx/issues/64

Where is your `.git` relative to your project?

**Comment by mathonsunday** [comment]
.git is at the same level as our MainProjectFolder and the Testing folder.

**Comment by marklarr** [comment]
Hey @mathonsunday,

Could you provide file trees for the following --

1) What the relevant areas of the xcode project looked like before Synx
2) What the relevant areas of project on disk looked like before Synx
3) What the relevant areas of the xcode project looked like after Synx (this should hopefully be the same as 1)
4) What the relevant areas of project on disk looked like after Synx

Thanks!

**Comment by mathonsunday** [comment]
Thanks for the response Mark. I  have decided to stop our team from using synx instead of sinking any more time into debugging the problem.
