### ISSUE TITLE
I encounter a problem "`initialize': can't convert Pathname into String (TypeError)"

### ISSUE THREAD

**Issue by qiaoxueshi** [venmo/synx#20]
The exception is as follows:
![image](https://cloud.githubusercontent.com/assets/622533/3156012/c31cebd4-ead0-11e3-8a2d-a7e4008e6ce0.png)

My command likes  `synx xxx.xcodeproj`, can u give me any suggestions? Thx

**Comment by marklarr** [comment]
I think this should be fixed now that variant groups are handled correctly in #63. Can you try again?

**Comment by marklarr** [comment]
I'm going to say it's safe to assume this is fixed now.
