### ISSUE TITLE
Support for Git Move/SVN Move, etc.

### ISSUE THREAD

**Issue by cnstoll** [venmo/synx#3]
First of all, grats on a great first release!

I'm sure you saw this coming, but support for various version control mv operations would be hugely helpful. That would allow this to be a common operation in a mature source control environment. As it is, I would consider this more of a "lets just fix this darn project" operation that I would run once initially rather than an ongoing maintenance tool.

**Comment by haojianzong** [comment]
I found synx may work well for git, it does not work for svn. After the moves, all svn histories will be lost.

Therefore I wrote a script to bridge "svn mv" so that it is possible to preserve svn histories.

Check: https://gist.github.com/haojianzong/5ab0ce86725f3785154d
