### ISSUE TITLE
xibs moved into wrong folder?

### ISSUE THREAD

**Issue by orta** [venmo/synx#33]
![screen shot 2014-07-14 at 11 56 42](https://cloud.githubusercontent.com/assets/49038/3569307/5dfbe006-0b3d-11e4-8de1-ea1df1e73205.png)

![screen shot 2014-07-14 at 11 58 04](https://cloud.githubusercontent.com/assets/49038/3569308/5ffe7c38-0b3d-11e4-88a5-6f3e6df173e2.png)

After a default `synx project.xcproject` I ended up with a lot of the xibs into what could have been the first reference for a folder for the xibs.

![screen shot 2014-07-14 at 12 04 11](https://cloud.githubusercontent.com/assets/49038/3569358/542c3ebc-0b3e-11e4-9872-ee2f98188371.png)

**Comment by marklarr** [comment]
This has been fixed and released in 0.0.6 via #63, thanks @archaeopterasa and everybody else!
