### ISSUE TITLE
Preserve the projects .pbxproj format

### ISSUE THREAD

**Issue by tapi** [venmo/synx#59]
It looks like when synx writes out the .pbxproj is writes it out as an XML plist.

Xcode of course can read this just fine but we're running into issues with the entire .pbxproj file being in conflict because apparently Xcode does not always convert it back to the native format.

**Comment by marklarr** [comment]
https://github.com/venmo/synx/issues/42#issuecomment-53685409

**Comment by kylef** [comment]
Misses this one before.

You can install `xcproj` via homebrew to make synx (and xcodeproj) save as ASCII plist.

https://github.com/CocoaPods/Xcodeproj/pull/203 may also be of some interest.
