### ISSUE TITLE
Add an option to flatten the hierarchy on disk, while retaining Xcode groups

### ISSUE THREAD

**Issue by tonyarnold** [venmo/synx#69]
I'd love to see an option to reverse the process — retain Xcode's groupings, but flatten all of the directories into a single folder.

**Comment by marklarr** [comment]
:scream: `unsynx`?

**Comment by tonyarnold** [comment]
:+1: _exactly_

**Comment by marklarr** [comment]
why would you want to do that?

**Comment by ayanonagon** [comment]
Whether this is something that people want or not, I don’t think this should be a part of `synx` since it kind of does the exact opposite thing that we want to do with `synx`. :grimacing:

**Comment by tonyarnold** [comment]
Why would I want all my classes stored hierarchically on disk? :trollface: 

Mainly because I prefer to store my classes in a single directory (they all have to have unique names anyway, right?) and once someone has run `synx` over a project it's really, really time consuming to reverse. 

I figured there was knowledge in this project of how I might go about flattening things back out.

Not to worry, thanks for your time guys.

**Comment by marklarr** [comment]
@tonyarnold I do agree with @ayanonagon that it doesn't really belong in synx. Most of the code in synx is logic around doing the actual synchronization.

That said, I think what you're proposing would be pretty easy. You just need to use the `xcodeproj` rubygem to loop over all of your Xcode objects and set their system path to the root, and then get rid of all of the system folders recursively. Maybe a separate ruby gem for that? If you have any questions, I'd be glad to help.

**Comment by tonyarnold** [comment]
Thanks @marklarr, I'll have a look at it later today and ask if I have any questions. Thanks :)

**Comment by marklarr** [comment]
Maybe the easiest option would be a fork of `synx` and then just poking around and changing lines until we get what we want. It wouldn't be the cleanest but it definitely would be fast
