### ISSUE TITLE
After synx some png will be can not find

### ISSUE THREAD

**Issue by sdyy** [venmo/synx#76]
After synx, some png will be can not find in the old location.
But even I remove the reference and remove the file and add again, it will show there is a same name file. But nothing is at there.

I use Xcode 6.3.

UPDATED:
It caused by I had duplicate reference, After synx, it removed duplicate reference. 
Then got the error.
Now I removed duplicate reference, then synx and it's OK.
Thanks for good tool.

**Comment by marklarr** [comment]
Thank you for the update!
