### ISSUE TITLE
[Question] Work with swift ?

### ISSUE THREAD

**Issue by DaRkD0G** [venmo/synx#92]
Hi, Work with swift ?

Thanks for your project :)

**Comment by AndrewSB** [comment]
It does

**Comment by kylef** [comment]
Thanks @AndrewSB, it should indeed work with Swift. Please file an appropriate bug if you find any specific problems with Swift sources @DaRkD0G.

**Comment by eonist** [comment]
Can synx update Xcode groups from finder structure. If I checkout something in git. It would be great if this was reflected in Xcode.
