### ISSUE TITLE
Request: Auto add non-referenced sources files to Xcode Project

### ISSUE THREAD

**Issue by foobra** [venmo/synx#96]
I've add one source file "foo.m" from another IDE(eg. Vim), after running synx, I wish synx auto add foo.m into Xcode Project and add it to "Compile Sources", can synx add this feature?

**Comment by marklarr** [comment]
That sounds like a useful tool, but it's a bit out of synx's wheelhouse. Off the top of my head, this would require knowing what target the file needs to be a part of. There may be other complexities, too. Might be better off to build something like this in a separate tool :)

**Comment by brendanjerwin** [comment]
@foobra did you ever find a solution for this?
